### ISSUE TITLE
Feature request: n-ary alts combinator

### ISSUE THREAD

**Issue by danr** [gcanti/parser-ts#12]
Do you think this combinator would fit?

```typescript
export function alts<A>(...ps: Parser<A>[]): Parser<A> {
  return ps.reduce((p1, p2) => p1.alt(p2), p.fail)
}
```

I find it improves readability over chaining `.alt`s.

NB: Would it be more efficient to use reduceRight and swap the order of the parsers to `alt`?

**Comment by gcanti** [comment]
Theoretically it could be derived by the `Foldable` module

```ts
import { parser } from 'parser-ts'
import { array } from 'fp-ts/lib/Array'
import { oneOf as oneOf_ } from 'fp-ts/lib/Foldable'

const oneOf = oneOf_(array, parser)
```

but I guess we could consolidate an optimized `oneOf` API since `array` is the most common instance of `Foldable`.

Would you like to send a PR?
