### ISSUE TITLE
(Ab)use await syntax to get do-notation-style chain?

### ISSUE THREAD

**Issue by danr** [gcanti/parser-ts#13]
Is it possible to augment the API so that `await` can be used for the `chain` function argument?

Consider this as an example:
```typescript
const space_padded = <A>(f: Parser<A>) =>
  pstr.spaces.chain(_ =>
  f.chain(a =>
  pstr.spaces.chain(_ => p.of(a))))
```

Then this could be written with `async`/`await` instead, making it look like Haskell do-notation:
```typescript
const space_padded = async <A>(f: Parser<A>) => {
  const _ = await pstr.spaces.chain
  const a = await f.chain
  const _ = await pstr.spaces.chain
  return a
}
```

Perhaps `Parser` could extend `Thenable` or `Promise` to be able to skip `chain` altogether:

```typescript
const space_padded = async <A>(f: Parser<A>) => {
  const _ = await pstr.spaces
  const a = await f
  const _ = await pstr.spaces
  return a
}
```

Would this be possible?

**Comment by gcanti** [comment]
> Would this be possible?

Honestly I don't know, I've never used `async` / `await`, looks like a hack though. Doesn't `async` always return a `Promise`?

**Comment by danr** [comment]
I was thinking about this a little more and I figured out a way to express approximately what I wanted using yield (I now think it is impossible to express this using async/await.) This generator idea is to yield parsers to another function to interpret. Here is an example of a combinator `seq` that tries to run the yielded parsers in sequence:

```typescript
const foobar: Parser<string> = seq<string>(function* () {
  return [
    yield sat(x => 'fb'.indexOf(x) != -1),
    yield sat(x => 'oa'.indexOf(x) != -1),
    yield sat(x => 'or'.indexOf(x) != -1),
  ].join('')
})
```

Here is some example input and output:

```typescript
console.dir(foobar('foo'))  // => { ok: true, s: '', a: 'foo' }
console.dir(foobar('bar'))  // => { ok: true, s: '', a: 'bar' }
console.dir(foobar('boo'))  // => { ok: true, s: '', a: 'boo' }
console.dir(foobar('baz'))  // => { ok: false, msg: 'sat failed: z' }
console.dir(foobar('fez'))  // => { ok: false, msg: 'sat failed: e' }
```

For completeness, here is the rest of this toy parser.

```typescript
type Result<A> = {ok: true, s: string, a: A} | {ok: false, msg: string}
type Parser<A> = (s: string) => Result<A>

function sat(p: (s: string) => boolean): Parser<string> {
  return s => {
    if (s.length == 0) {
      return {ok: false, msg: 'unexpected end of string'}
    } else if (!p(s[0])) {
      return {ok: false, msg: 'sat failed: ' + s[0]}
    } else {
      return {ok: true, s: s.slice(1), a: s[0]}
    }
  }
}

function seq<A>(invocations: () => IterableIterator<Parser<any> | A>): Parser<A> {
  return s => {
    const iter = invocations()
    let rem = s
    let r: IteratorResult<Parser<any> | A>
    let next: any = undefined
    while (r = iter.next(next)) {
      if (typeof r.value === 'function') {
        const res = (r.value as Parser<any>)(rem)
        if (res.ok) {
          rem = res.s
          next = res.a
        } else {
          return res
        }
      } else {
        return {ok: true, s: rem, a: r.value}
      }
    }
    return {ok: false, msg: 'seq did not return a value'}
  }
}
```

## Discussion

Unfortunately TypeScript does not type results from yield at all. I'm not sure it actually can without using existential types.

**Comment by teves-castro** [comment]
Hi @danr, I too have been looking into this, first using both the approaches you took (async/await) but couldn't make it work. Then using generators I managed to get an acceptable syntax but lacking type safety.
I finally ended up writing a small library that also supplies an acceptable syntax, works for most of the monads supplied by fp-ts, it's easy to extend (I lately added an instance for this parser lib) and it improves readability of these long chains.

**Comment by danr** [comment]
Hi @teves-castro , thanks for the heads up, I had a look at your `ts-do` repo and it is very interesting. One thing that struck me is that it's possible to use the record creating syntax to avoid the string literal:

```typescript
   .for({ys: ({ x }) => range(0, x).map(() => some(1))}) 
```

instead of:

```typescript
   .for("ys", ({ x }) => range(0, x).map(() => some(1))) 
```
   
Anyway, closing this since this is now quite unrelated to parser-ts.

**Comment by teves-castro** [comment]
@danr thank you for the suggestion. I also looked into this option, but couldn't make it work. I couldn't convince the typescript type inference engine that the argument for the function on the supplied record was of the threaded context type, forcing the caller to supply the type for that context on the lambda. :(
