### ISSUE TITLE
feature request: `between` and `surroundedBy`

### ISSUE THREAD

**Issue by CYBAI** [gcanti/parser-ts#21]
Would you think it's a good idea to add these 2 combinators into `Parser`?
It might be useful for parsing things like (for example) phone number in format `(123)-456-789`.

https://github.com/ekmett/parsers/blob/0bbae073a36c338f8205f529db3bbd94f297ba91/src/Text/Parser/Combinators.hs#L123-L135

In TS, it might look like

```ts
export function between<I, A>(begin: Parser<I, A>, end: Parser<I, A>, p: Parser<I, A>): Parser<I, A> {
  return Do(parser)
    .do(begin)
    .bind('content', p)
    .do(end)
    .return(({ content }) => content);
}

export function surroundedBy<I, A>(bound: Parser<I, A>, p: Parser<I, A>): Parser<I, A> {
  return between(bound, bound, p);
}
```

**Comment by gcanti** [comment]
@CYBAI :+1:

**Comment by IMax153** [comment]
@CYBAI This addition would be excellent in my opinion! I found myself often wanting a `between` parser in a different project, so I wrote one as well.

It only uses combinators from `parser-ts`, so it would prevent having to include `fp-ts-contrib` as a dependency of `parser-ts`. I also partially apply both the `between` and `surroundedBy` parsers to make them more flexible. I figured I would share my implementation in case you found it useful!

```typescript
import { pipe } from 'fp-ts/lib/function'
import { chain, chainFirst, Parser } from 'parser-ts/lib/Parser'

export const between = <I, A>(left: Parser<I, A>, right: Parser<I, A>) => (
  parser: Parser<I, A>
): Parser<I, A> =>
  pipe(
    left,
    chain(() => parser),
    chainFirst(() => right)
  )

export const surroundedBy = <I, A>(bound: Parser<I, A>): ((parser: Parser<I, A>) => Parser<I, A>) =>
  between(bound, bound)
```

**Comment by YBogomolov** [comment]
It really is funny how this project became active *exactly* at the time I had to write a parser at my job! 😆 I was really happy about the new release.

However, it maybe more convenient to have `parser` parameter to be polymorphic in its parsed type. Consider an example:

```ts
// <Term> ::= <Word> | 'NOT (' <Word> ')'
type Term =
  | { readonly tag: 'Word'; readonly value: string; }
  | { readonly tag: 'Not'; readonly value: Term; }

const Word: Parser<string, Term> = pipe(
  textWithoutSpaces,
  alt(() => doubleQuotedString),
  map((value) => ({ tag: 'Word', value }))
);

const braced = between(char('('), char(')')); // => Parser<string, string>

const NotWord = braced(Word); // ❌
// Argument of type 'Parser<string, Term>' is not assignable to parameter of type 'Parser<string, string>'
```

Better implementation would be the following:

```ts
const between = <I, A>(left: Parser<I, A>, right: Parser<I, A>) => <B>(p: Parser<I, B>) => pipe(
  left,
  chain(() => p),
  chainFirst(() => right)
);
```

@gcanti @IMax153 I can send a PR for this enhancement?

**Comment by CYBAI** [comment]
@IMax153 thanks for the PR! and sorry for being busy recently and didn't have time to send one.
@YBogomolov Yes! I thinks making it polymorphic should be good! 👀
