### ISSUE TITLE
export run from test/helpers.ts

### ISSUE THREAD

**Issue by waynevanson** [gcanti/parser-ts#33]
The `run` function is handy for users writing their own tests, but it is not exposed to users consuming the module.

Would you accept a PR expose it?

**Comment by gcanti** [comment]
Do you mean the `run` function in `code-frame.ts`?

**Comment by gcanti** [comment]
~Do you mean the `run` function in `code-frame.ts`?~

Never mind, I didn't pay attention to the title...

> Would you accept a PR expose it?

:+1:
