### ISSUE TITLE
Design Question: Stream with Positioned Tokens

### ISSUE THREAD

**Issue by IMax153** [gcanti/parser-ts#37]
@gcanti - If you are willing, I would like to have a design discussion about how the problem described below can potentially be solved using `parser-ts` in the most efficient manner.

## Question

How can I create a `Stream` in which I have access to the position of a given token (i.e. the line and column number) in the most efficient manner possible.

## Description of the Issue

I would like to create a group of parsers that are aware of and can respond to the current indentation level, similar to how a Python parser needs to detect when the indentation level increases or decreases. Because the parser I am trying to create is *context-sensitive*, I am not sure the problem can be easily solved with `parser-ts`. However, I can think of two approaches that would at least allow me access to the position of tokens within a `Stream`. 

## Current State

The problem proposed above inherently lends itself to a `Parser` with a `string` source that parses a `Stream` of `Char`s. Therefore, when referring to parsers below I am actually referring to a parser of string characters:

```typescript
import { Char } from 'parser-ts/Char'

type StringParser<A> = Parser<Char, A>
```

Within a `Stream`, we have access to the current `cursor` position which allows us to determine our current position within the buffer of unparsed character tokens. However, the cursor is unaware of the actual position of a character token within a given piece of source text. 

## Possible Solutions

Both solutions involve adding an additional piece of data to the `Stream` generated for a given `Parser`. In this case, the additional piece of data is the `Pos` interface described below.

```typescript
/**
 * Represents the position of a token within the source text.
 */
export interface Pos {
  readonly line: number
  readonly col: number
}
```

Given a character and the previous position, the position of the character in question can be determined using the functions below:

```typescript
/**
 * Constructs a new `Pos` given a line number and a column number.
 */
export const pos = (line: number, col: number): Pos => ({
  line,
  col
})

/**
 * The initial `Pos` within any source text.
 */
export const initialPos = pos(1, 1)

/**
 * Updates the `Pos` given a character and the previous `Pos` in the source text.
 */
export const updatePosChar: (c: Char, pos: Pos) => Pos = (char, { line, col }) => {
  switch (char) {
    case '\n':
      return pos(line + 1, 1)
    case '\r':
      return pos(line + 1, 1)
    case '\t':
      return pos(line, col + 8 - ((col - 1) % 8))
    default:
      return pos(line, col + 1)
  }
}
```

#### Solution 1

The first solution that I came up with involves modifying the type of data stored in the `buffer` of a `Stream`. 

```typescript
import { Char } from 'parser-ts/Char'
import { Pos } from 'parser-ts/Pos'
import { Stream } from 'parser-ts/Stream'

/**
 * Represents a character and its associated position with the source text.
 */
export interface PositionedChar {
  readonly char: Char
  readonly pos: Pos
}

/**
 * Represents a stream of positioned characters.
 */
export type CharStream = Stream<PositionedChar>
``` 

The buffer of positioned characters must be created ahead of time by first splitting the source text into an array of character tokens, and then mapping the resulting array into an array of `PositionedChar`s. The inefficiency of the solution follows from the two separate passes through the stream of character tokens.

#### Solution 2

The second solution involves modification of the source code of `parser-ts` to include the `Pos` module as well as a new `CharStream` module given how common it is to use `parser-ts` on a stream of character tokens.

The proposed code for the `CharStream` module can be found below.

```typescript
import { lookup } from 'fp-ts/lib/Array'
import { map, Option } from 'fp-ts/lib/Option'
import { pipe } from 'fp-ts/lib/function'

import { Char } from './char'
import { Pos, updatePosChar } from './Pos'

export interface CharStream {
  readonly buffer: Array<Char>
  readonly pos: Pos
  readonly cursor: number
}

export const charStream: (buffer: Array<Char>, pos: Pos, cursor?: number) => CharStream = (
  buffer,
  pos,
  cursor = 0
) => ({
  buffer,
  pos,
  cursor
})

export const get: (s: CharStream) => Option<Char> = s => lookup(s.cursor, s.buffer)

export const atEnd: (s: CharStream) => boolean = s => s.cursor >= s.buffer.length

export const getAndNext: (s: CharStream) => Option<{ readonly value: Char; readonly next: CharStream }> = s =>
  pipe(
    get(s),
    map(a => ({ value: a, next: charStream(s.buffer, updatePosChar(a, s.pos), s.cursor + 1) }))
  )
```

Please let me know if you think that this type of context-sensitive parsing is out of scope for `parser-ts`. I am very curious to hear your thoughts!

**Comment by gcanti** [comment]
> The buffer of positioned characters must be created ahead of time by first splitting the source text into an array of character tokens, and then mapping the resulting array into an array of PositionedChars. The inefficiency of the solution follows from the two separate passes through the stream of character tokens.

The `CharStream` creation can be optimized though

```ts
export function getCharStream(s: string): CharStream {
  const buffer: Array<PositionedChar> = []
  let p: Pos = pos(1, 0)
  for (let char of s) {
    buffer.push({
      char,
      pos: p = updatePosChar(char, p)
    })
  }
  return stream(buffer)
}
```

**Comment by IMax153** [comment]
Sorry for leaving this open for so long - I will close now as this solution works for me!
