### ISSUE TITLE
Feature Request: manyTill and many1Till

### ISSUE THREAD

**Issue by IMax153** [gcanti/parser-ts#38]
## Problem Statement
The `manyTill` and `many1Till` combinators from [`purescript-string-parsers`](https://github.com/purescript-contrib/purescript-string-parsers/blob/main/src/Text/Parsing/StringParser/Combinators.purs#L149) allow for writing some interesting parsers.

```purescript
-- | Parse values until a terminator.
manyTill :: forall a end. Parser a -> Parser end -> Parser (List a)

-- | Parse values until the terminator matches, requiring at least one match.
many1Till :: forall a end. Parser a -> Parser end -> Parser (NonEmptyList a)
```

For example, if we were writing an HTML parser and wanted to define a parser that could parse HTML comments, per the spec we would have to adhere to the following:
> 12.1.6 Comments
> Comments must have the following format:
>
> 1. The string "", or "--!>", nor end with the string "<!-".
> 3. The string "-->".
> 
> Note: The text is allowed to end with the string "<!", as in "\".

My initial thought was to utilize the new `filter` combinator that we added in #30. This would work for rejecting invalid characters or strings encountered within the comment. However, because any other character is valid we would not have a reliable way of telling the parser to stop after the "-->" sequence.

## Discussion

Under the hood, `purescript-string-parsers` uses the [`MonadRec`](https://github.com/purescript-contrib/purescript-string-parsers/blob/main/src/Text/Parsing/StringParser.purs#L85) type class to handle recursively iterating through the stream and accumulating values until the terminator parser is encountered.

I implemented a similar solution using the `ChainRec` type class from `fp-ts`. 

```typescript
import { tailRec } from 'fp-ts/ChainRec'
import * as E from 'fp-ts/Either'
import { error, success, ParseResult, ParseSuccess } from 'parser-ts/ParseResult'
import * as P from 'parser-ts/Parser'
import { Stream } from 'parser-ts/Stream'

interface Next<I, A> {
  readonly value: A
  readonly stream: Stream<I>
}

const chainRec = <I, A, B>(a: A, f: (a: A) => P.Parser<I, E.Either<A, B>>): P.Parser<I, B> => {
  const split = (result: ParseSuccess<I, E.Either<A, B>>): E.Either<Next<I, A>, ParseResult<I, B>> =>
    E.isLeft(result.value)
      ? E.left({ value: result.value.left, stream: result.next })
      : E.right(success(result.value.right, result.next, result.start))

  return (i) => tailRec({ value: a, stream: i }, (state) => {
    const result = f(state.value)(state.stream)
    if (E.isLeft(result)) {
      return E.right(error(state.stream))
    }
    return split(result.right)
  })
}
```

## Solution

This allows us to define `manyTill` and `many1Till` in terms of `chainRec`.

```typescript
import * as RA from 'fp-ts/ReadonlyArray'
import * as RNEA from 'fp-ts/ReadonlyNonEmptyArray'

export const manyTill = <I, A, B>(
  parser: P.Parser<I, A>,
  terminator: P.Parser<I, B>
): P.Parser<I, ReadonlyArray<A>> =>
  pipe(
    terminator,
    P.map<B, ReadonlyArray<A>>(() => RA.empty),
    P.alt<I, ReadonlyArray<A>>(() => many1Till(parser, terminator))
  )

export const many1Till = <I, A, B>(
  parser: P.Parser<I, A>,
  terminator: P.Parser<I, B>
): P.Parser<I, RNEA.ReadonlyNonEmptyArray<A>> => {
  return pipe(
    parser,
    P.chain((x) =>
      chainRec(RNEA.of(x), (acc) =>
        pipe(
          terminator,
          P.map(() => E.right(RNEA.reverse(acc))),
          P.alt(() =>
            pipe(
              parser,
              P.map((a) => E.left(RNEA.cons(a, acc)))
            )
          )
        )
      )
    )
  )
}
```

@gcanti  - I am curious what you think of my approach above. I know that `ChainRec` is marked for removal in `fp-ts@v3` but it worked nicely for this use case. What would your thoughts be on adding these to the main library? Do you think these can be improved/cleaned up further?

**Comment by gcanti** [comment]
> What would your thoughts be on adding these to the main library?

:+1:

> Do you think these can be improved/cleaned up further?

Not sure about `RNEA.cons` and then `RNEA.reverse`, can't we use `RNEA.snoc` instead?

```ts
export const many1Till = <I, A, B>(
  parser: P.Parser<I, A>,
  terminator: P.Parser<I, B>
): P.Parser<I, RNEA.ReadonlyNonEmptyArray<A>> => {
  return pipe(
    parser,
    P.chain(x =>
      chainRec(RNEA.of(x), acc =>
        pipe(
          terminator,
          P.map(() => E.right(acc)),
          P.alt(() =>
            pipe(
              parser,
              P.map(a => E.left(RNEA.snoc(acc, a)))
            )
          )
        )
      )
    )
  )
}
```

**Comment by IMax153** [comment]
> Not sure about `RNEA.cons` and then `RNEA.reverse`, can't we use `RNEA.snoc` instead?

Yes, I believe you are completely correct! I'll get a PR ready with the changes you recommended implemented as well as some test cases.
