### ISSUE TITLE
Fatal error from filter

### ISSUE THREAD

**Issue by techtangents** [gcanti/parser-ts#43]
I'd like to be able to raise a fatal error from a `filter` combinator. Perhaps we could add some optional parameters for `filter` which pass through options to `error`.

Happy to contribute code if you accept the feature.

**Comment by IMax153** [comment]
Hey @techtangents! You can force any `Parser` to produce a `fatal` error using the `cut` combinator.

```ts
/**
 * The `cut` parser combinator takes a parser and produces a new parser for
 * which all errors are fatal, causing either to stop trying further
 * parsers and return immediately with a fatal error.
 */
declare const cut: <I, A>(p: Parser<I, A>) => Parser<I, A>
```

Without `cut`:

```ts
import { pipe } from 'fp-ts/function'
import * as P from 'parser-ts/Parser'
import { stream } from 'parser-ts/Stream'

const parser = pipe(
  P.item<string>(),
  P.filter((c) => c === 'a')
)
console.log(parser(stream(['a'])))
//                                                               Error is non-fatal -----v
// => { _tag: 'Left', left: { input: { buffer: ['b'], cursor: 0 }, expected:[], fatal: false } }
```

With cut:

```ts
import { pipe } from 'fp-ts/function'
import * as P from 'parser-ts/Parser'
import { stream } from 'parser-ts/Stream'

const parser = pipe(
  P.item<string>(),
  P.filter((c) => c === 'a'),
  P.cut 
)
console.log(parser(stream(['a'])))
//                                                                   Error is fatal -----v
// => { _tag: 'Left', left: { input: { buffer: ['b'], cursor: 0 }, expected:[], fatal: false } }
```

**Comment by techtangents** [comment]
With my use case, I have code like this:

```
code parses = pipe(
  parser1,
  P.filter(...)
)
```

Now, if the first parser fails, I want it to fail non-fatal. If the filter fails, I want that to be fatal.

**Comment by IMax153** [comment]
Ah, I see - in that case I would chain the first `Parser` and then use `cut` on the subsequent `Parser`. 

Here is a contrived example (there are definitely better ways to achieve the same logic):

```ts
import { pipe } from 'fp-ts/function'
import * as C from 'parser-ts/char'
import * as P from 'parser-ts/Parser'
import { stream } from 'parser-ts/Stream'

const parser1 = C.oneOf('abc')

const parser = pipe(
  parser1,
  P.chain((a) => 
    pipe(
      P.of<string, string>(a),
      P.filter((u) => u === 'a'),
      P.cut
    )
  )
)

console.log(parser(stream('d'.split(''))))                                                                        
// { 
//   _tag: 'Left', 
//   left: { 
//     input: { 
//       buffer: ['a'], 
//       cursor: 0 
//     }, 
//     expected: ["One of \"abc\""], 
//     fatal: false // First parser fails, error is non-fatal
//   } 
// }

console.log(parser(stream('b'.split(''))))
// { 
//   _tag: 'Left', 
//   left: { 
//     input: { 
//       buffer: ['b'], 
//       cursor: 0 
//     }, 
//     expected: [], 
//     fatal: true // Second parser fails, error is non-fatal
//   } 
// }
```

**Comment by techtangents** [comment]
Yeah, that works. Thanks.

I was hoping to have that logic in a single combinator in the library. 

I ended up writing the following:

```
export const hardFilter: {
  <A, B extends A>(refinement: Refinement<A, B>): <I>(p: Parser<I, A>) => Parser<I, B>
  <A>(predicate: Predicate<A>): <I>(p: Parser<I, A>) => Parser<I, A>
} = <A>(predicate: Predicate<A>) => <I>(p: Parser<I, A>): Parser<I, A> => (i) =>
  pipe(
    p(i),
    E.chain(next => (predicate(next.value) ? E.right(next) : ParseResult.error(i, undefined, true)))
  );
```

**Comment by IMax153** [comment]
I don't necessarily have a problem with adding this to the library, I have just never run across a use case where I needed something like this. 

I may be able to provide a better alternative/solution if you can to provide additional context as to what you are attempting to parse!

In any case, if @gcanti is okay with a PR to add this combinator to the library, my only suggestion would be to rename it to `filterCut` (to follow the current convention for escalating a `Parser` error).

**Comment by techtangents** [comment]
Thanks for your help @IMax153. I think, at this point, since I have 2 workarounds, I can't argue that this is a high priority.

**Comment by IMax153** [comment]
Alright, I will close this issue for now but if it becomes a larger issue in the future feel free to open and we can more formally address it!
